import logo from './../logo.png';

export default function AboutUs() {
    return (
        <div>
            <h1 style={{ fontWeight: 900 }}>About Us :</h1>
            <div className="logo">
                <img src={logo} />
            </div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at tortor ut leo dapibus dignissim. Mauris ultricies eu nisi et semper. Maecenas viverra dolor sem, sed egestas mi iaculis eu. Pellentesque nec placerat ex. Maecenas pretium vestibulum leo, in ultricies dolor cursus ac. Nunc cursus tempus commodo. Aliquam erat volutpat. Suspendisse lobortis aliquet porta. Nunc auctor neque vel viverra tincidunt. Nulla rutrum ex quis metus iaculis suscipit. Donec efficitur mi vitae est egestas, in rutrum neque imperdiet. Curabitur ex ipsum, volutpat ut pretium vitae, dapibus sed elit. Nulla sapien sem, consequat ac massa in, commodo sagittis libero. Nunc tristique erat vitae mauris finibus, quis consequat ante accumsan. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis vitae felis et mi facilisis malesuada.</p>
            <p>Sed laoreet nisl leo, ut vestibulum magna porttitor aliquam. Praesent interdum nulla sed finibus sodales. Suspendisse ut diam in leo congue porta. Nunc vel tellus nulla. Phasellus quis congue nibh. Praesent pretium eros at consequat mattis. Sed suscipit metus at nunc gravida ultricies. Donec gravida tempor bibendum. Morbi velit diam, facilisis quis nibh at, aliquet maximus nisl. Morbi molestie fermentum sem vitae placerat. Nulla vestibulum rutrum purus. Maecenas quis nisl sed lorem convallis vehicula. In egestas dolor felis, eget venenatis augue egestas in.</p>
            <p>Etiam vitae ex eget metus aliquet finibus id ac urna. Donec id est lorem. Aliquam vitae lacinia lectus, ac posuere quam. Morbi interdum faucibus eros, vitae rhoncus purus placerat in. Mauris at facilisis dui. Morbi sodales purus dapibus lacus volutpat accumsan. Donec sit amet enim pellentesque sem molestie fringilla. Integer blandit sed augue vel congue. Suspendisse volutpat elementum nibh, at luctus justo pulvinar nec. Pellentesque at ornare diam, at viverra orci. Mauris lacinia dictum metus ut ornare. Pellentesque interdum sed tortor non aliquam.</p>
            <p>Fusce lacinia quam nibh, sodales varius est tempor quis. Curabitur dui lacus, tristique dictum elit in, laoreet eleifend dolor. Pellentesque eu bibendum justo. Vivamus sed dolor semper, aliquet metus aliquet, vulputate felis. Vivamus convallis neque pellentesque, consectetur lorem eget, hendrerit nulla. Etiam risus mi, pretium in felis ac, sollicitudin efficitur urna. Aliquam erat volutpat. Nulla dapibus vehicula dolor at semper. Ut molestie, arcu ac tristique varius, mi nibh viverra augue, ut mattis magna arcu in orci. Maecenas id ex vel turpis consequat mollis nec nec dolor.</p>
            <p>Aenean efficitur et lacus quis mollis. Donec non aliquet sem. Duis tincidunt massa sed scelerisque consequat. Aliquam ultrices nec nulla eu semper. Pellentesque est lacus, consectetur sed mauris vitae, lobortis consequat turpis. Etiam sed metus ultrices, consectetur velit at, lobortis magna. Ut vitae neque sed quam ultrices pharetra. Aenean neque dolor, laoreet sagittis leo nec, accumsan suscipit felis. Nullam non dui sit amet dolor aliquet aliquam vitae hendrerit elit. Curabitur mattis tempor odio eu iaculis. Sed risus diam, interdum eget tristique nec, sodales vel metus. Etiam interdum sem eu velit vehicula, et sollicitudin orci consectetur.</p>
        </div>
    );
}